name: alien-siege-app # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Alien Siege Attack
summary: Defend Earth from alien invasion forces.
description: Strategize defense tactics and battle waves of extraterrestrials to protect humanity. Upgrade weapons and unlock abilities to survive.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  alien-siege-app:
    command: bin/alien-siege-app-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  alien-siege-app:
    plugin: dump
    source: .
    organize:
      alien-siege-app-bin: bin/
